# Generated by Django 4.1 on 2022-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_account_manager",
            field=models.BooleanField(
                default=True, verbose_name="account manager status"
            ),
        ),
    ]
