# Generated by Django 4.1 on 2022-08-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="is_directors_approval",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="is_directors_approval",
            field=models.CharField(max_length=3),
        ),
    ]
